In [2]:
!pip install scikit-learn
import pandas as pd
import numpy as np
from sklearn import linear_model

Requirement already satisfied: scikit-learn in c:\users\shoaib nisar\anaconda\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\shoaib nisar\anaconda\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\shoaib nisar\anaconda\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\shoaib nisar\anaconda\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\shoaib nisar\anaconda\lib\site-packages (from scikit-learn) (3.5.0)

In [3]:
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('hiring.csv')

In [5]:
df.head

<bound method NDFrame.head of   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000>

In [6]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [7]:
df.experience=df.experience.fillna("zero")

In [8]:
import math
median_test_score=df['test_score(out of 10)'].median()

In [9]:
median_test_score

8.0

In [10]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_test_score)

In [11]:
pip install word2number

Collecting word2number
  Using cached word2number-1.1-py3-none-any.whl
Installing collected packages: word2number
Successfully installed word2number-1.1
Note: you may need to restart the kernel to use updated packages.

In [12]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [13]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
from word2number import w2n
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [15]:
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [16]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [18]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [19]:
reg.intercept_

17737.26346433768

In [20]:
reg.predict([[2,9,6]])

c:\Users\Shoaib Nisar\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53205.96797671])

In [21]:
reg.predict([[12,10,10]])

c:\Users\Shoaib Nisar\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([92002.18340611])

In [24]:
%matplotlib inline
plt.xlabel('experience_test_interview')
plt.ylabel('salary')
plt.scatter(df['experience'], df['salary($)'] ,color='red')
plt.scatter(df['test_score(out of 10)'], df['salary($)'] ,color='blue')
plt.scatter(df['interview_score(out of 10)'], df['salary($)'] ,color='green')